[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
derive_more = { version = "2.0.1", features = ["display", "from", "into"] }
fraction = "0.15.3"
itertools = "0.14.0"
num = "0.4.3"
num_enum = "0.7.3"
